home page links and buttons validation test
inventa-shop/qa-test-prod pull request #36
Opened 2022-11-11 20:24 UTC by NataliaSantosB

# Description

Home page all links and buttons validation test

https://app.qase.io/project/ACQ?view=1&suite=5&case=33&previewMode=modal
https://app.qase.io/project/ACQ?view=1&suite=5&case=34&previewMode=modal
https://app.qase.io/project/ACQ?view=1&suite=5&case=35&previewMode=modal

# Checklist:

- [x] New tests

2022-11-11 20:39 UTC, andreyAut commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +    it.only ('Categories', () =>{
Remember that "**only**" runs this test only. If you want to run the others, remember to remove the "only"

2022-11-11 20:40 UTC, andreyAut commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +            //cy.contains('h1', text).should('exist')   //ESTA PEGANDO O NOME COM FORMATACAO
this comment, I believe you can remove it from here.

2022-11-14 11:01 UTC, NataliaSantosB commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +    it.only ('Categories', () =>{
Thank you Andrey. I will remove all

2022-11-16 12:07 UTC, CaiqueCoelho requested changes
Excellent Pull Request, I have left just minor improvements you can implement

2022-11-21 14:44 UTC, NataliaSantosB commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +            //cy.contains('h1', text).should('exist')   //ESTA PEGANDO O NOME COM FORMATACAO
Made the necessary adjustment to the code and it has already been removed.

2022-11-21 14:47 UTC, NataliaSantosB commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +        cy.contains('Fornecedor').should('have.attr','href').and('include', '/pages/fornecedor')
Made the necessary adjustment to the code and it has already been removed.

2022-11-21 14:47 UTC, NataliaSantosB commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +        cy.contains('Contato').should('have.attr','href').and('include', '/pages/contato')
Made the necessary adjustment to the code and it has already been removed.

2022-11-21 14:47 UTC, NataliaSantosB commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +        cy.contains('Painel Fornecedor').should('have.attr','href').and('include', 'https://fornecedor.inventa.app.br')
Made the necessary adjustment to the code and it has already been removed.

2022-11-21 15:05 UTC, NataliaSantosB commented on cypress/integration/ProdTests/Homefull.test.spec.js
> +            cy.contains('h1', text).should('exist')
Made the necessary adjustment in the code

2022-11-21 15:13 UTC, andreyAut approved these changes

2022-11-23 03:29 UTC, CaiqueCoelho approved these changes

2022-11-23 13:48 UTC, merged